<a href="https://colab.research.google.com/github/Pomoirab/ML/blob/main/teachers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data = open('drive/My Drive/University of Bradford/Teaching/Artificial Intelligence Module/Supervised Learning/teachers.txt').read().split('\n')
texts = []
labels = []
for line in data:
  line = line.split('|')
  if len(line) != 2:
    continue
  text = line[0].strip()
  label = line[1].strip()
  texts.append(text)
  labels.append(label)

In [ ]:
len(texts), len(labels)

(10, 10)

In [ ]:
texts

['The teacher was disrespectful and he treats everyone badly',
 'This teacher treats people with disrespect . She always yells at her students',
 'Please tell him not to yell as us',
 'He needs to respect us . We are humans .',
 'If he treats his students like that , then we should not respect him',
 'What a wonderful teacher',
 'This lady is wonderful . She explains the lessons in a very easy to understand way',
 'The way she explains things is really great',
 'She is the most wonderful teacher I have seen in my life',
 'I wish all my teacher were like that . She makes everything easy']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)

In [ ]:
 vectorizer.get_feature_names_out()

array(['all', 'always', 'and', 'are', 'as', 'at', 'badly', 'disrespect',
       'disrespectful', 'easy', 'everyone', 'everything', 'explains',
       'great', 'have', 'he', 'her', 'him', 'his', 'humans', 'if', 'in',
       'is', 'lady', 'lessons', 'life', 'like', 'makes', 'most', 'my',
       'needs', 'not', 'people', 'please', 'really', 'respect', 'seen',
       'she', 'should', 'students', 'teacher', 'tell', 'that', 'the',
       'then', 'things', 'this', 'to', 'treats', 'understand', 'us',
       'very', 'was', 'way', 'we', 'were', 'what', 'wish', 'with',
       'wonderful', 'yell', 'yells'], dtype=object)

In [ ]:
 print(X.toarray())

[[0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 1 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0
  0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1
  0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1
  0 0 1 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 1 0 0 1 1 0 1 0 1 0 1 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0
  0 1 0 0 0 0 0 1 0 1 0

In [ ]:
 vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(1, 3))
 X2 = vectorizer2.fit_transform(data)
 vectorizer2.get_feature_names_out()

array(['all', 'all my', 'all my teacher', 'always', 'always yells',
       'always yells at', 'and', 'and he', 'and he treats', 'are',
       'are humans', 'are humans neg', 'as', 'as us', 'as us neg', 'at',
       'at her', 'at her students', 'badly', 'badly neg', 'disrespect',
       'disrespect she', 'disrespect she always', 'disrespectful',
       'disrespectful and', 'disrespectful and he', 'easy', 'easy pos',
       'easy to', 'easy to understand', 'everyone', 'everyone badly',
       'everyone badly neg', 'everything', 'everything easy',
       'everything easy pos', 'explains', 'explains the',
       'explains the lessons', 'explains things', 'explains things is',
       'great', 'great pos', 'have', 'have seen', 'have seen in', 'he',
       'he needs', 'he needs to', 'he treats', 'he treats everyone',
       'he treats his', 'her', 'her students', 'her students neg', 'him',
       'him neg', 'him not', 'him not to', 'his', 'his students',
       'his students like', 'humans', 

In [ ]:
 print(X2.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]]


We will now train machine learners to do sentiment analysis

In [ ]:
# A KNN classifier
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, labels)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
test1 = ["This wonderful teacher is a mster of making hard subjects easy . I like her"]
test1_vec = vectorizer.transform(test1)
test1_vec.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]])

In [ ]:
print(neigh.predict(test1_vec))

['POS']


In [ ]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X, labels)

LogisticRegression()

In [ ]:
print(clf.predict(test1_vec))

['POS']


In [ ]:
import numpy as np
odds = np.exp(clf.coef_)
words = vectorizer.get_feature_names_out()

In [ ]:
odds[0]

array([1.15360155, 0.83827647, 0.82914019, 0.8668889 , 0.84958543,
       0.83827647, 0.82914019, 0.83827647, 0.82914019, 1.26612674,
       0.82914019, 1.15360155, 1.27241013, 1.15932652, 1.09960212,
       0.65725396, 0.83827647, 0.7768709 , 0.91441176, 0.8668889 ,
       0.91441176, 1.20686007, 1.39914488, 1.09754251, 1.09754251,
       1.09960212, 1.05486682, 1.15360155, 1.09960212, 1.2685027 ,
       0.8668889 , 0.7768709 , 0.83827647, 0.84958543, 1.15932652,
       0.79269341, 1.09960212, 1.35302491, 0.91441176, 0.76652987,
       1.16697117, 0.84958543, 1.05486682, 1.16008725, 0.91441176,
       1.15932652, 0.92004406, 0.80833586, 0.63556072, 1.09754251,
       0.73649618, 1.09754251, 0.82914019, 1.27241013, 0.79269341,
       1.15360155, 1.32359003, 1.15360155, 0.83827647, 1.59738795,
       0.84958543, 0.83827647])

In [ ]:
words

array(['all', 'always', 'and', 'are', 'as', 'at', 'badly', 'disrespect',
       'disrespectful', 'easy', 'everyone', 'everything', 'explains',
       'great', 'have', 'he', 'her', 'him', 'his', 'humans', 'if', 'in',
       'is', 'lady', 'lessons', 'life', 'like', 'makes', 'most', 'my',
       'needs', 'not', 'people', 'please', 'really', 'respect', 'seen',
       'she', 'should', 'students', 'teacher', 'tell', 'that', 'the',
       'then', 'things', 'this', 'to', 'treats', 'understand', 'us',
       'very', 'was', 'way', 'we', 'were', 'what', 'wish', 'with',
       'wonderful', 'yell', 'yells'], dtype=object)

In [ ]:
for x, y in sorted(zip(odds[0], words)):
  print(x, y)

0.6355607189079368 treats
0.6572539649389394 he
0.7364961780017127 us
0.7665298650476123 students
0.7768709045695091 him
0.7768709045695091 not
0.7926934092344861 respect
0.7926934092344861 we
0.8083358644401715 to
0.8291401912545957 and
0.8291401912545957 badly
0.8291401912545957 disrespectful
0.8291401912545957 everyone
0.8291401912545957 was
0.8382764721750412 always
0.8382764721750412 at
0.8382764721750412 disrespect
0.8382764721750412 her
0.8382764721750412 people
0.8382764721750412 with
0.8382764721750412 yells
0.8495854250603928 as
0.8495854250603928 please
0.8495854250603928 tell
0.8495854250603928 yell
0.8668889040196975 are
0.8668889040196975 humans
0.8668889040196975 needs
0.9144117609059562 his
0.9144117609059562 if
0.9144117609059562 should
0.9144117609059562 then
0.9200440640628734 this
1.054866821582904 like
1.054866821582904 that
1.09754251085644 lady
1.09754251085644 lessons
1.09754251085644 understand
1.09754251085644 very
1.0996021158769624 have
1.0996021158769624 li